name: Gerar Dashboard RH

on:
  push:
    paths:
      - 'dados/*.xlsx'
      - 'gerar_dashboard.py'
      - '.github/workflows/deploy.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        pip install pandas openpyxl

    - name: Gerar Dashboard
      run: |
        python gerar_dashboard.py

    - name: Commit e push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Atualiza dashboard automaticamente" || echo "Nada para commitar"
        git push
